### ISSUE TITLE
Nightwatch driver compatibility 📸 

### ISSUE THREAD

**Issue by MadeinFrance** [percy/percy-appium-js#145]
My tests are running fine with `WebdriverIO` but with `Nightwatch` I can't locate/share the driver for Percy snapshot.

```js
it('pass the login', async function (app) {
    const myElement = await app.element.find(
      new By('accessibility id', 'login-button'),
    );

    // console.log(await myElement.takeScreenshot());
    // NOT WORKING
    // await percyScreenshot(myElement, 'Login');

    // NOT WORKING
    // await percyScreenshot(app.driver, 'Login');


    // working with WebdriverIO to snapshot the screen
    await percyScreenshot('Login');
  });
});
```

The exact error is when Percy is trying to evaluate the `remoteHostname` variable of the driver. 
`TypeError: Cannot read properties of undefined (reading 'includes')`

See https://github.com/percy/percy-appium-js/blob/49c9170900ba86225a0c21c6e2cebe22d496511c/percy/providers/appAutomateProvider.js#L14

Note:
The `app.driver` property returns a similar object:

```js
WebDriver {
  session_: Promise {
    Session {
      id_: '9deba3ae-403b-4901-8318-33d8420db750',
      caps_: [Capabilities]
    }
  },
  executor_: Executor {
    customCommands_: null,
    log_: Logger {
      name_: 'webdriver.http.Executor',
      level_: null,
      parent_: [Logger],
      handlers_: null
    },
    w3c: true
  },
  fileDetector_: null,
  onQuit_: undefined,
  authenticatorId_: null,
  pinnedScripts_: {}
}
```

**Comment by ninadbstack** [comment]
Hey @MadeinFrance ! thanks for pointing this out, we do not support Nightwatch driver as of now. We will have to go through the Nightwatch driver object and find replacements for all functions that we call on standard appium/wdio driver. 

Support for nightwatch driver is already acknowledged as a feature request and is on our product roadmap.

**Comment by ninadbstack** [comment]
Hey @MadeinFrance ! the reason why percy does not support this is because we need to tag all images with correct environment information, like device, os, screensize, navbar/status bar height etc and we get all of that information from the driver at runtime when `percyScreenshot` is called. [ Thats how devices show up on percy dashboard and multiple device screenshots are clubbed together under a snapshot ]

If you want to use this with NightwatchJS by passing base64 of the screenshot, it certainly is possible with a wrapper.   
Please have a look at https://github.com/percy/example-percy-appium-js/blob/ninad/manual-upload-poc/manual/manual_upload.js 

You can copy the `mockDriver` function and edit it accordingly to send all the other correct metadata [ in linked file that metadata is loaded from a json file, its a poc branch for uploading images from folder ]
One other change you will have to do is instead of `screenshotPath` you can directly pass `screenshotBase64` as an argument [ `mockDriver` anyway reads the file as base64 ] 

let me know if you need any more help with this.

**Comment by ninadbstack** [comment]
Closing this as workaround is provided.
@MadeinFrance  I would also recommend to open a support ticket with browserstack to add Nightwatch driver support, so that we can add first class support for the same.
